create database LIBRARY
CHARACTER SET utf8
COLLATE utf8_general_ci;

USE LIBRARY;

CREATE TABLE USER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DATEOFBIRTH DATE,
    RETURNDUEDATE DATE,
    WORKPLACE TEXT,
    MAJOR VARCHAR(50)
);

CREATE TABLE ACCOUNT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME CHAR(50),
    PASSWORD CHAR(50),
    USERID INT,

    FOREIGN KEY(USERID) REFERENCES USER(ID)
);

CREATE TABLE BORROWEDBOOK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ACCID INT,
    CODE CHAR(50),p
    BOOKID INT,

    FOREIGN KEY(ACCID) REFERENCES ACCOUNT(ID),
    FOREIGN KEY(BOOKID) REFERENCES BOOKINFO(ID),
);

CREATE TABLE BOOKINFO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE CHAR(50),
    AUTHOR CHAR(50),
    PUBLISHER CHAR(50),
    PUBLISHEDYEAR INT,
    RATINGS INT,
    COMMENT TEXT,
    BRANCHID INT,
    AMOUNT INT,

    FOREIGN KEY (BRANCHID) REFERENCES BRANCH(ID)
);

CREATE TABLE BRANCH (
    ID INT PRIMARY KEY,
    NAME CHAR(50)
)